services:
# Datacenter 1 (DC1) Server
  dc1s1:
    image: dev-consul
    container_name: dc1s1
    hostname: dc1s1
    privileged: true
    networks:
      dc1:
        ipv4_address: 10.1.10.1
      # wan:
      #   ipv4_address: 10.10.10.1
    ports:
      - "8500:8500"
      - "2345:2345"
    volumes:
      - ./conf/:/conf/
    environment:
      # mute annoying latest version check on startup
      - CHECKPOINT_DISABLE=true 
    #command: "consul agent -dev -bind=10.1.10.1 -config-file=/conf/dc1s1.hcl"
    #command: "consul agent -dev -config-file=/conf/dc1s1.hcl"
    #command: "consul agent -config-file=/conf/dc1s1.hcl"
    command: "/root/go/bin/dlv exec /usr/local/bin/consul --continue --accept-multiclient --headless --listen=:2345 --api-version=2 --log -- agent -config-file=/conf/dc1s1.hcl"

# Ingress gateway for DC1
  dc1igw1:
    restart: unless-stopped
    image: dev-consul
    container_name: dc1igw1
    privileged: true
    environment:
      - CHECKPOINT_DISABLE=true 
    ports:
      - "4567:4567"
    networks:
      dc1:
        ipv4_address: 10.1.10.2
      wan:
        ipv4_address: 10.10.10.2
    volumes:
      - ./conf/:/conf/
    command: "sh -c '/conf/start-ingress-gw.sh /conf/dc1a1.hcl 10.1.10.1:8301'"

# Service1 for DC1
  dc1svc1:
    restart: unless-stopped  
    image: dev-consul
    container_name: dc1svc1
    privileged: true
    environment:
      - CHECKPOINT_DISABLE=true 
    networks:
      dc1:
        ipv4_address: 10.1.10.3
    ports:
      - "9001:9001" # The service port forwards
      - "19001:19000" # The Envoy ports forwards
    volumes:
      - ./conf/:/conf/
    command: "sh -c '/conf/startsvc.sh /conf/dc1a2.hcl 10.1.10.1:8301 /conf/dc1svc1.hcl dc1-svc1' "

networks:
  dc1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
  wan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16