apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: static-server
spec:
  subsets:
    v1:
      filter: Service.Meta.version == 1
    v2:
      filter: Service.Meta.version == 2
  defaultSubset: v1