services:
  # Datacenter 1 (DC1) Server
  dc1s1:
    image: dev-consul-enterprise
    container_name: dc1s1
    privileged: true
    networks:
      dc1:
        ipv4_address: 10.1.10.1
      wan:
        ipv4_address: 10.10.10.1
    ports:
      - "8500:8500"
    volumes:
      - ../../secrets/:/license/
      - ./conf/:/conf/
    environment:
      CONSUL_LICENSE_PATH: /license/consul_license.txt
    command: consul agent -bind 10.10.10.1 -serf-wan-bind 10.10.10.1 -advertise-wan 10.10.10.1 -client 10.1.10.1 -dev -config-file=/conf/dc1s1.hcl -retry-join-wan 10.10.20.1

#  # Service for DC1
#  dc1svc1:
#    image: dev-consul-enterprise
#    container_name: dc1svc1
#    privileged: true
#    networks:
#      dc1:
#        ipv4_address: 10.1.10.3
#      wan:
#        ipv4_address: 10.10.10.3
#    ports:
#      - "9001:9001" # The service port forwards
#      - "19001:19000" # The Envoy ports forwards
#    volumes:
#      - ../../secrets/:/license/
#      - ./conf/:/conf/
#    environment:
#      CONSUL_LICENSE_PATH: /license/consul_license.txt
#    command: "sh -c '/conf/startsvc.sh /conf/dc1a2.hcl 10.1.10.1:8301 /conf/dc1svc1.hcl dc1-svc1' "

  # Datacenter 2 (DC2)
  dc2s1:
    image: dev-consul-enterprise
    container_name: dc2s1
    privileged: true
    networks:
      dc2:
        ipv4_address: 10.2.10.1
      wan:
        ipv4_address: 10.10.20.1
    ports:
      - "9500:8500"
    volumes:
      - ../../secrets/:/license/
      - ./conf/:/conf/
    environment:
      CONSUL_LICENSE_PATH: /license/consul_license.txt
    command: consul agent -bind 10.10.20.1 -serf-wan-bind 10.10.20.1 -advertise-wan 10.10.20.1 -client 10.2.10.1 -config-file=/conf/dc2s1.hcl -retry-join-wan 10.10.10.1
#
#  dc2svc1:
#    image: dev-consul-enterprise
#    container_name: dc2svc1
#    privileged: true
#    networks:
#      dc2:
#        ipv4_address: 10.2.10.3
#      wan:
#        ipv4_address: 10.10.20.3
#    volumes:
#      - ../../secrets/:/license/
#      - ./conf/:/conf/
#    environment:
#      CONSUL_LICENSE_PATH: /license/consul_license.txt
#    command: "sh -c '/conf/startsvc.sh /conf/dc2a2.hcl 10.2.10.1:8301 /conf/dc2svc1.hcl dc2-svc1' "

networks:
  dc1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
  dc2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/16
  wan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16